- platform: template
  lights:
    balcony_light:
      friendly_name: 'Свет на балконе'
      value_template: >-
        {% if is_state('switch.balcony_light', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.balcony_light
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.balcony_light

- platform: template
  lights:
    summer_terrace_light:
      friendly_name: 'Свет на террасе'
      value_template: >-
        {% if is_state('switch.summer_terrace_light', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.summer_terrace_light
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.summer_terrace_light

- platform: template
  lights:
    yard_light_at_balcony:
      friendly_name: 'Свет во дворе'
      value_template: >-
        {% if is_state('switch.yard_light_at_balcony', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.yard_light_at_balcony
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.yard_light_at_balcony