- platform: switch
  name: hall_light_main
  entity_id: switch.hall_light_main

- platform: switch
  name: hall_light_sub
  entity_id: switch.hall_light_sub

- platform: switch
  name: yard_light_at_balcony
  entity_id: switch.yard_light_at_balcony

- platform: switch
  name: summer_terrace_light
  entity_id: switch.summer_terrace_light

- platform: switch
  name: porch_light_main
  entity_id: switch.porch_light_main

- platform: switch
  name: porch_light_sub
  entity_id: switch.porch_light_sub

- platform: switch
  name: balcony_light
  entity_id: switch.balcony_light

- platform: switch
  name: kitchen_light_main
  entity_id: switch.kitchen_light_main

- platform: switch
  name: kitchen_light_sub
  entity_id: switch.kitchen_light_sub

- platform: switch
  name: loft_light_main
  entity_id: switch.loft_light_main

- platform: switch
  name: loft_light_sub
  entity_id: switch.loft_light_sub

- platform: switch
  name: garage_light
  entity_id: switch.garage_light

- platform: switch
  name: kitchen_coridor_light
  entity_id: switch.kitchen_coridor_light

- platform: switch
  name: torsher
  entity_id: switch.torsher
  