- alias: garage light auto on
  trigger: 
  - platform: state
    entity_id: binary_sensor.garage_motion_sensor
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.garage_light


- alias: garage light auto off
  trigger: 
  - platform: state
    entity_id: binary_sensor.garage_motion_sensor
    to: 'off'
    for:
      minutes: 20
  action:
    service: switch.turn_off
    entity_id: switch.garage_light