- alias: Replace Buttery
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.hall_motion_sensor_battery_level
      - sensor.summer_kitchen_motion_sensor_battery_level
      - sensor.porch_motion_sensor_battery_level
      - sensor.loft_motion_sensor_battery_level
      - sensor.loft_smoke_sensor_battery_level
      - sensor.hall_smoke_sensor_battery_level
      - sensor.kitchen_smoke_sensor_battery_level
      - sensor.garage_smoke_sensor_battery_level
      - sensor.kitchen_flood_sensor_battery_level
      - sensor.garage_motion_sensor_battery_level
      - sensor.kitchen_motion_sensor_battery_level
    below: 10
  action:
    - service: notify.telegram
      data_template:
        title: "Села батарейка"
        message: "{{ trigger.to_state.attributes['friendly_name'] | string }}"
